version: '3'
services:
  api:
    image: golang:1.20
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    ports: 
      - "5432:5432"

